import jenan from '../../Images/jenan.jpg'

const PostData = [
    {
        id: 1,
        name: "Khadeejah Hamdan",
        addres: "Amman, Jordan",
        image: '/Images/khadeja.jpg',
        imagePost: '/Images/post1.png',
        user1: "Mohammad AlShwaiki",
        coment1: "مقابله ولا اروع من هيك فعلا انهم رهيبيين 😁 شكرا على الاستضافة😊",
        user2: "Amal Al-Dajah ",
        coment2: "كتييير كنت مبسوطة لما شفتكم و طايرة من الفرح 😍🤩",
    },
    {
        id: 2,
        name: "Ashraf Al Jabari",
        addres: "Amman, Jordan",
        image: '/Images/ashraf.jpg',
        imagePost: '/Images/pp.jpg',
        user1: "Ashraf Al Jabari",
        coment1: "الحمد لله صرت الهوست 😇🥳🤩😎 .. معكم الهوست 😌",
        user2: "Monther-Twaissi ",
        coment2: "والله منور ههههههه شكللك امبوستر 👻",
    },
    {
        id: 3,
        name: "Hadeel Alshahwan",
        addres: "Amman, Jordan",
        image: '/Images/hadeel.jpg',
        imagePost: '/Images/post5.jpeg',
        user1: "Hadeel Alshahwan",
        coment1: "دائما بنشتغل على التعاون و المحبه بين الطلاب و هاي الصورة وحدة من اللحظات الجميله الي مرينا فيها بالكوهورت 🥳🥰😌",
        user2: "Taima Alfokaha ",
        coment2: "شكرا كتير اصدقائي فعلا اكاديمية اورنج هي بيتنا التاني الي نفسنا نداوم فيها 😂😍",
    },
    {
        id: 4,
        name: "Taima alfokaha",
        addres: "Amman, Jordan",
        image: '/Images/71769659.jpg',
        imagePost: '/Images/post4.png',
        user1: "Taima alfokaha",
        coment1: "لو كنت ناسي أفكرك 😂😂",
        user2: "Ahmad E'mar",
        coment2: "يا جماعة انا مروح 🏃🏻‍♂️",
    },
    {
        id: 5,
        name: "Razan Zuaiter",
        addres: "Amman, Jordan",
        image: '/Images/razan.png',
        imagePost: '/Images/post6.jpeg',
        user1: "Razan Zuaiter",
        coment1: "أيام مكنا كلاس سي 🥰🤩 وقتها تخرجت من الجامعه 😂",
        user2: "Jenan Musallam",
        coment2: "أشكالنا بتضحك كلنا 😂😂",
    },
    {
        id: 6,
        name: "	Mohammad Bdour ",
        addres: "Amman, Jordan",
        image: '/Images/bdor.jpg',
        imagePost: '/Images/post7.png',
        user1: "Abdel rahman Abdaldeen",
        coment1: "بدي اشغلك ياها ان شاء الله 😎👻😂",
        user2: "Amal Al-Dajah ",
        coment2: "كتييير  مبسوطة 🥰🤩 ",
    },
    {
        id: 7,
        name: "	Sarah Al-Eswed",
        addres: "Amman, Jordan",
        image: '/Images/sara.jpeg',
        imagePost: '/Images/1.jpg',
        user1: "Sarah Al-Eswed",
        coment1: "يوم كتيير لطيف 🥰",
        user2: "Monther-Twaissi ",
        coment2: "شكله مش حنرجع عليه 😂😂😂😂",
    },
    {
        id: 8,
        name: "	Ayah_Abd_Aljawad",
        addres: "Amman, Jordan",
        image: '/Images/ayah.jpeg',
        imagePost: '/Images/1920-6.jpg',
        user1: "Ayah_Abd_Aljawad",
        coment1: "لازم نعمل رياضة كل يوم عشان جسمنا يضل نشيط 😁🏃🏻‍♂️🏃🏻‍♂️",
        user2: "Ahmad AlAsad ",
        coment2: "شكرا على التمارين اللطيفه 😁",
    },
    {
        id: 9,
        name: "	Dana Toughoj",
        addres: "Amman, Jordan",
        image: '/Images/dana.jpg',
        imagePost: '/Images/post10.jpg',
        user1: "Dana Toughoj",
        coment1: "صدقوني مو أنا الامبوستر 🙄🥺👻",
        user2: "Abdel rahman Abdaldeen",
        coment2: "خلينا نطلعها انتو بس ردو علي 🤓",
    },
    {
        id: 10,
        name: "Jenan Musallam",
        addres: "Amman, Jordan",
        image: jenan,
        imagePost: '/Images/post9.jpg',
        user1: "Jenan Musallam",
        coment1: "كتير مفيد الليمون و الملح ",
        user2: "	Ayah_Abd_Aljawad",
        coment2: "أكيد أكيد 😎",
    },

];
export default PostData;
